"""create init tables

Revision ID: 71da29053525
Revises: 
Create Date: 2021-03-16 20:55:43.386196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71da29053525'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile',
    sa.Column('id', sa.Unicode(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('updated', sa.DATETIME(), nullable=True),
    sa.Column('city', sa.Unicode(), nullable=True),
    sa.Column('first_name', sa.Unicode(), nullable=True),
    sa.Column('last_name', sa.Unicode(), nullable=True),
    sa.Column('headline', sa.Unicode(), nullable=True),
    sa.Column('state', sa.Unicode(), nullable=True),
    sa.Column('summary', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course',
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('number', sa.Unicode(), nullable=True),
    sa.Column('profile_id', sa.Unicode(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    op.drop_table('profile')
    # ### end Alembic commands ###
