"""create extra tables

Revision ID: fbdba4d9cfec
Revises: 71da29053525
Create Date: 2021-03-17 00:27:30.587700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbdba4d9cfec'
down_revision = '71da29053525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('updated', sa.DATETIME(), nullable=True),
    sa.Column('starts_at', sa.DATETIME(), nullable=True),
    sa.Column('ends_at', sa.DATETIME(), nullable=True),
    sa.Column('field_of_study', sa.Unicode(), nullable=True),
    sa.Column('degree_name', sa.Unicode(), nullable=True),
    sa.Column('school', sa.Unicode(), nullable=True),
    sa.Column('school_profile_url', sa.Unicode(), nullable=True),
    sa.Column('profile_id', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experience',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('updated', sa.DATETIME(), nullable=True),
    sa.Column('starts_at', sa.DATETIME(), nullable=True),
    sa.Column('ends_at', sa.DATETIME(), nullable=True),
    sa.Column('company', sa.Unicode(), nullable=True),
    sa.Column('company_profile_url', sa.Unicode(), nullable=True),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('location', sa.Unicode(), nullable=True),
    sa.Column('profile_id', sa.Unicode(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('honour_award',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('updated', sa.DATETIME(), nullable=True),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('issuer', sa.Unicode(), nullable=True),
    sa.Column('issued_on', sa.DATETIME(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('profile_id', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('updated', sa.DATETIME(), nullable=True),
    sa.Column('profile_id', sa.Unicode(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('updated', sa.DATETIME(), nullable=True),
    sa.Column('profile_id', sa.Unicode(), nullable=True),
    sa.Column('starts_at', sa.DATETIME(), nullable=True),
    sa.Column('ends_at', sa.DATETIME(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patent',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('updated', sa.DATETIME(), nullable=True),
    sa.Column('profile_id', sa.Unicode(), nullable=True),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('url', sa.Unicode(), nullable=True),
    sa.Column('issued_on', sa.DATETIME(), nullable=True),
    sa.Column('issuer', sa.Unicode(), nullable=True),
    sa.Column('patent_number', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('updated', sa.DATETIME(), nullable=True),
    sa.Column('profile_id', sa.Unicode(), nullable=True),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('url', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publication',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('updated', sa.DATETIME(), nullable=True),
    sa.Column('profile_id', sa.Unicode(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('publisher', sa.Unicode(), nullable=True),
    sa.Column('published_on', sa.DATETIME(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('url', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_score',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('updated', sa.DATETIME(), nullable=True),
    sa.Column('profile_id', sa.Unicode(), nullable=True),
    sa.Column('name', sa.Unicode(), nullable=True),
    sa.Column('score', sa.Unicode(), nullable=True),
    sa.Column('date_on', sa.DATETIME(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteering_experience',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created', sa.DATETIME(), nullable=True),
    sa.Column('updated', sa.DATETIME(), nullable=True),
    sa.Column('profile_id', sa.Unicode(), nullable=True),
    sa.Column('starts_at', sa.DATETIME(), nullable=True),
    sa.Column('ends_at', sa.DATETIME(), nullable=True),
    sa.Column('cause', sa.Unicode(), nullable=True),
    sa.Column('company', sa.Unicode(), nullable=True),
    sa.Column('company_profile_url', sa.Unicode(), nullable=True),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('location', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('volunteering_experience')
    op.drop_table('test_score')
    op.drop_table('publication')
    op.drop_table('project')
    op.drop_table('patent')
    op.drop_table('organization')
    op.drop_table('language')
    op.drop_table('honour_award')
    op.drop_table('experience')
    op.drop_table('education')
    # ### end Alembic commands ###
